---
os_tuning_packages:
  - procps

os_tuning_sysctl_defaults:
  vm.swappiness: "10"
  vm.dirty_background_ratio: "10"
  vm.dirty_ratio: "20"
  fs.inotify.max_user_watches: "524288"
  net.core.netdev_max_backlog: "4096"
  net.core.somaxconn: "4096"

os_tuning_sysctl_overrides: {}

os_tuning_journald_storage: "persistent"
os_tuning_journald_system_max_use: "1G"
os_tuning_journald_vacuum_size: "1G"

os_tuning_dphys_swap_size_mb: ""

os_tuning_swapfile_enabled: false
os_tuning_swapfile_size: "1G"
